# Generated by Django 2.2 on 2021-12-07 03:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nId_person', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nId_person', models.CharField(max_length=100, verbose_name='รหัส')),
                ('cGender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('ด.ช', 'ด.ช'), ('ด.ญ', 'ด.ญ')], default='ชาย', max_length=19, verbose_name='เพศ')),
                ('cFname', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('nAge', models.IntegerField(blank=True, null=True, verbose_name='อายุ')),
                ('cLevel', models.CharField(choices=[('เตี่ยนฉวนซือ', 'เตี่ยนฉวนซือ'), ('เจี่ยงซือ', 'เจี่ยงซือ'), ('ถันจู่', 'ถันจู่'), ('เจี่ยงเอี๋ยน', 'เจี่ยงเอี๋ยน'), ('พุทธบริกร', 'พุทธบริกร')], default='พุทธบริกร', max_length=100, verbose_name='ธรรมวุฒิ')),
                ('cEdu', models.CharField(choices=[('ป.เอก', 'ป.เอก'), ('ป.โท', 'ป.โท'), ('ป.ตรี', 'ป.ตรี'), ('ปวส', 'ปวส'), ('ปวท', 'ปวท'), ('ปวช', 'ปวช'), ('มัธยม', 'มัธยม'), ('ประถม', 'ประถม'), ('อนุบาล', 'อนุบาล'), ('ไม่ได้เรียน', 'ไม่ได้เรียน'), ('ไม่แจ้ง', 'ไม่แจ้ง')], default='ไม่แจ้ง', max_length=100, verbose_name='การศึกษา')),
                ('cCareer', models.CharField(choices=[('เกษตรกร', 'เกษตรกร'), ('เกษียณ', 'เกษียณ'), ('ขายอาหารเจ', 'ขายอาหารเจ'), ('ข้าราชการบำนาญ', 'ข้าราชการบำนาญ'), ('ครู/อาจารย์', 'ครู/อาจารย์'), ('ค้าขาย', 'ค้าขาย'), ('ธนาคาร', 'ธนาคาร'), ('แพทย์/พยาบาล', 'แพทย์/พยาบาล'), ('ตำรวจ/ทหาร', 'ตำรวจ/ทหาร'), ('ธุรกิจส่วนตัว/อิสระ', 'ธุรกิจส่วนตัว/อิสระ'), ('พนักงานบริษัท', 'พนักงานบริษัท'), ('พนักงานรัฐวิสาหกิจ', 'พนักงานรัฐวิสาหกิจ'), ('พ่อบ้าน', 'พ่อบ้าน'), ('แม่บ้าน', 'แม่บ้าน'), ('รับจ้าง', 'รับจ้าง'), ('รับราชการ', 'รับราชการ'), ('นักเรียน', 'นักเรียน'), ('นักศึกษา', 'นักศึกษา'), ('อื่นๆ', 'อื่นๆ')], default='อื่นๆ', max_length=100, verbose_name='อาชีพ')),
                ('cRoom', models.CharField(blank=True, max_length=100, null=True, verbose_name='พุทธสถาน')),
                ('cRoom_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='พุทธสถาน(จีน)')),
                ('cPro', models.CharField(choices=[('จางเหวินฟ่ง', 'จางเหวินฟ่ง'), ('จางชุ่ยเหวิน', 'จางชุ่ยเหวิน'), ('เฉินจวิ้นสยง', 'เฉินจวิ้นสยง'), ('หลี่ซิ่วอวี้', 'หลี่ซิ่วอวี้'), ('สวีลี่หย่ง', 'สวีลี่หย่ง')], default='สวีลี่หย่ง', max_length=100, verbose_name='อ.ถ่ายทอดเบิกธรรม')),
                ('cPro_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.ถ่ายทอดเบิกธรรม(จีน)')),
                ('cDate_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='วันรับธรรมะ(ภาษาจีน)')),
                ('cDate_dc', models.CharField(blank=True, max_length=100, null=True, verbose_name='วันรับธรรมะ(จีน)')),
                ('cTdate', models.CharField(blank=True, max_length=100, null=True, verbose_name='วันรับธรรมะ(ไทย)')),
                ('dDate', models.DateField(blank=True, null=True, verbose_name='วันรับธรรมะ')),
                ('cRec', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.แนะนำ')),
                ('cSup', models.CharField(blank=True, max_length=100, null=True, verbose_name='อ.รับรอง')),
                ('cAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='ที่อยู่')),
                ('cMtel', models.CharField(blank=True, max_length=100, null=True, verbose_name='โทรศัพท์มือถือ')),
                ('cHtel', models.CharField(blank=True, max_length=100, null=True, verbose_name='โทรศัพท์บ้าน')),
                ('cName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อจีน')),
                ('c3dd', models.CharField(blank=True, max_length=100, null=True)),
                ('c3dl', models.CharField(blank=True, max_length=100, null=True)),
                ('cMd', models.CharField(blank=True, max_length=100, null=True)),
                ('cMl', models.CharField(blank=True, max_length=100, null=True)),
                ('cSd', models.CharField(blank=True, max_length=100, null=True)),
                ('cSl', models.CharField(blank=True, max_length=100, null=True)),
                ('cJd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJl', models.CharField(blank=True, max_length=100, null=True)),
                ('cPt1', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt2', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt3', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt4', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt5', models.CharField(blank=True, max_length=3, null=True)),
                ('cPt6', models.CharField(blank=True, max_length=3, null=True)),
                ('cCd', models.CharField(blank=True, max_length=100, null=True)),
                ('cCl', models.CharField(blank=True, max_length=100, null=True)),
                ('cCp', models.CharField(blank=True, max_length=100, null=True)),
                ('cUd', models.CharField(blank=True, max_length=100, null=True)),
                ('cUl', models.CharField(blank=True, max_length=100, null=True)),
                ('cUp', models.CharField(blank=True, max_length=100, null=True)),
                ('cRd', models.CharField(blank=True, max_length=100, null=True)),
                ('cRl', models.CharField(blank=True, max_length=100, null=True)),
                ('cRp', models.CharField(blank=True, max_length=100, null=True)),
                ('cPd', models.CharField(blank=True, max_length=100, null=True)),
                ('cPl', models.CharField(blank=True, max_length=100, null=True)),
                ('cPp', models.CharField(blank=True, max_length=100, null=True)),
                ('cJvd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJvl', models.CharField(blank=True, max_length=100, null=True)),
                ('cJvp', models.CharField(blank=True, max_length=100, null=True)),
                ('cTjd', models.CharField(blank=True, max_length=100, null=True)),
                ('cTjl', models.CharField(blank=True, max_length=100, null=True)),
                ('cTjp', models.CharField(blank=True, max_length=100, null=True)),
                ('cJcd', models.CharField(blank=True, max_length=100, null=True)),
                ('cJcl', models.CharField(blank=True, max_length=100, null=True)),
                ('cJcp', models.CharField(blank=True, max_length=100, null=True)),
                ('cPrd', models.CharField(blank=True, max_length=100, null=True)),
                ('cPrl', models.CharField(blank=True, max_length=100, null=True)),
                ('cPrp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=225)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bkk1',
            fields=[
                ('tableall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.TableAll')),
            ],
            bases=('app.tableall',),
        ),
        migrations.CreateModel(
            name='Skw1',
            fields=[
                ('tableall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.TableAll')),
            ],
            bases=('app.tableall',),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(default=1, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bkk1001',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Bkk1002',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Bkk1003',
            fields=[
                ('bkk1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Bkk1')),
            ],
            bases=('app.bkk1',),
        ),
        migrations.CreateModel(
            name='Skw1001',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Skw1')),
            ],
            bases=('app.skw1',),
        ),
        migrations.CreateModel(
            name='Skw1002',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Skw1')),
            ],
            bases=('app.skw1',),
        ),
        migrations.CreateModel(
            name='Skw1003',
            fields=[
                ('skw1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Skw1')),
            ],
            bases=('app.skw1',),
        ),
    ]
